// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCANXiBn44AC2PAVx0P_4s1ZvKJy1Ac8nk',
    appId: '1:541712904242:android:d17a7232d8d75065234c2b',
    messagingSenderId: '541712904242',
    projectId: 'flockergymapp',
    databaseURL: 'https://flockergymapp-default-rtdb.firebaseio.com',
    storageBucket: 'flockergymapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFF-cOqTpbAP06pVi6jZ9Y6IH3kbH7YFI',
    appId: '1:541712904242:ios:075c8bfcb50f9e27234c2b',
    messagingSenderId: '541712904242',
    projectId: 'flockergymapp',
    databaseURL: 'https://flockergymapp-default-rtdb.firebaseio.com',
    storageBucket: 'flockergymapp.appspot.com',
    iosClientId: '541712904242-f87ajl7nm66ukijmr23ltq60uuli9k6v.apps.googleusercontent.com',
    iosBundleId: 'com.flockerlabs.flockergym',
  );
}
